### PR TITLE
Dot at event

### PR DESCRIPTION
**Pull request by vhlee7**
## Description

Fixes issue #126 

findDotAtEvent now finds position of dot at specific beats of a stuntsheet. 
I added a beat variable and the function checks for the dot's position at that beat.

There is an issue that came up where sometimes the mouse is not able to click/find the dot.
To replicate, increment and decrement the beats and sometimes you will be unable to click on a dot.

## Pre-PR checklist

- [x] Ran `npm run serve` and:
  - [x] Checked basic functionality
  - [ ] Checked that errors are handled
- [x] Ran `npm run lint`
- [x] Ran `npm run test:unit`
- [ ] Ran `npm run test:e2e` and ran relevant tests
- [ ] Attached reviewers to PR and pinged on Slack/email

## Screenshots/GIFs

[Attach screenshots if making a visible change!]

### CODE REVIEW

**Comment by rmpowell77** [comment]
it might be nice to have a unit test for this.

**Review by MichaelTamaki — APPROVED** [review]
Nice work! Please add a unit test like Richard suggested!

**Comment by adhamrait** [comment]
I'm still getting an issue with the lasso tool:

ezgif-3-ce5d6446d20b


I think this can be fixed at line 92 of ToolSelectMove

**Comment by vhlee7** [comment]
Thank you for all the feedback!

**Comment by vhlee7** [comment]
can merge, make another pr for unit tests
fix to dot repositioning issue: can't move dots when not on hup beat

**Pull request merged**
